spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/appointment_engine_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000

---

spring:
  profiles: dev
server:
  port: 8080

---

spring:
  profiles: prod
  datasource:
    platform: postgres
    url: jdbc:postgresql://postgresql:5432/appointment_engine_db
    username: postgres
    password: postgres
server:
  port: 0
