version: '3'
services:
  backend:
    image: dudnikvad/aptm-backend
    build: .
    ports:
    - "8080:8080"
  postgres:
    image: postgres
    restart: always
    environment:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: appointment_engine_db

